// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DissapearFooterController from "./dissapear_footer_controller"
application.register("dissapear-footer", DissapearFooterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
